### ISSUE TITLE
[Feature] Create Waiting Check Page

### ISSUE THREAD

**Issue by ohchanju3** [LINE-NOW/LINENOW-Web#18]
## 🛠 Issue
웨이팅 체크 페이지 UI를 구현합니다.

## 📝 To-do
- [ ] 인원 수 체크 컴포넌트 개발
- [ ] 줄서기 정보 확인 페이지 개발
- [ ] 줄서기 최종 확인 컴포넌트 개발
