### ISSUE TITLE
[Feature] Create A Feature Of Items - Setting Page

### ISSUE THREAD

**Issue by ZZZINU** [LINE-NOW/LINENOW-Web#42]
## 🛠 Issue

Setting 페이지 안의 아이템들의 기능들을 구현합니다. 

## 📝 To-do
- [x] 이용약관 링크 이동
- [x] 1:1 문의 링크 이동
- [x] 개발자 정보 링크 이동
