### ISSUE TITLE
[Fix] Fixing Waiting Card 

### ISSUE THREAD

**Issue by shimseohyun** [LINE-NOW/LINENOW-Web#55]
## 🛠 Issue
waiting card 내 오류들을 해결합니다

## 📝 To-do
- [x] 대기 취소된 waiting card 클릭 안되게 변경하기
- [x] api 명세서에 맞게 수정
- [x] use Waiting Card config 리펙토링
